### ISSUE TITLE
Add light and Darkmode

### ISSUE THREAD

**Issue by idna001** [idna001/Couple-Memory#32]
# Overview 
Light and Dark mode with use of System Preference 
Default: dark 

Info Material:
https://dev.to/ayc0/light-dark-mode-system-mode-user-preferences-1fcd

# Tasks

- [ ] Look up the Info 
- [ ] Add the logic
- [ ] Test that everything still works as before
- [ ] Please also look up the Mobile Viewport

**Comment by Surajit0573** [comment]
I can do it. Can you assign it to me !!
